In [1]:
import numpy as np
import pandas as pd

# Exercise 1

In [2]:
pd.__version__

'1.4.4'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-10-01 21:32:38--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.2’

car_fuel_efficiency 100%[===================>] 853,70K  --.-KB/s    in 0,04s   

2025-10-01 21:32:39 (18,7 MB/s) - ‘car_fuel_efficiency.csv.2’ saved [874188/874188]



In [4]:
data = pd.read_csv('car_fuel_efficiency.csv')
data.head(30)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   170            3.0       159.0     3413.433759   
1                   130            5.0        97.0     3149.664934   
2                   170            NaN        78.0     3079.038997   
3                   220            4.0         NaN     2542.392402   
4                   210            1.0       140.0     3460.870990   
5                   190            3.0         NaN     2484.883986   
6                   240            7.0       127.0     3006.542287   
7                   150            4.0       239.0     3638.657780   
8                   250            1.0       174.0     2714.219310   
9                   150            4.0       123.0     3509.036569   
10                  230            5.0       100.0     3111.810181   
11                  150            5.0         NaN     1967.200421   
12                  320            5.0       145.0     2783.868974   
13                  170            1.0       193.0     2274.735191   
14                  200            6.0       160.0     3582.687368   
15                  220            4.0       179.0     2631.065204   
16                  160            3.0       180.0     2673.552941   
17                  190            6.0       132.0     2427.311856   
18                  250            2.0       110.0     2971.214575   
19                  180            1.0       126.0     2986.958657   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   
22                  190            1.0       144.0     2438.842126   
23                  230            2.0       160.0     3342.606027   
24                  260            3.0       156.0     4267.390497   
25                  210            6.0       157.0     2860.206191   
26                  180            8.0       160.0     3080.170162   
27                  120            6.0       206.0     3467.355490   
28                  220            4.0       154.0     3335.068187   
29                  230            4.0       132.0     2479.782974   

    acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0           17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1           17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2           15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3           20.2        2009     USA    Diesel    All-wheel drive        2.0   
4           14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5           14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6           22.2        2012     USA  Gasoline  Front-wheel drive        1.0   
7           17.3        2020     USA    Diesel    All-wheel drive        1.0   
8           10.3        2016    Asia    Diesel  Front-wheel drive       -1.0   
9           10.2        2005     USA  Gasoline  Front-wheel drive       -1.0   
10          15.4        2014  Europe    Diesel    All-wheel drive        0.0   
11          12.6        2014     USA    Diesel  Front-wheel drive        2.0   
12          15.1        2010    Asia    Diesel    All-wheel drive        1.0   
13          17.5        2000  Europe    Diesel  Front-wheel drive        0.0   
14          14.9        2007    Asia    Diesel    All-wheel drive        0.0   
15          16.0        2006     USA  Gasoline    All-wheel drive        1.0   
16           8.5        2013  Europe    Diesel    All-wheel drive       -1.0   
17          17.8        2011     USA    Diesel  Front-wheel drive       -1.0   
18           NaN        2003  Europe  Gasoline  Front-wheel drive        1.0   
19          17.9        2004  Europe  Gasoline    All-wheel drive       -1.0   
20          18.7        2011    Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016    Asia  Gasoline  Front-wheel drive       -

# Exercise 2

In [5]:
len(data)

9704

# Exercise 3

In [6]:
len(data.fuel_type.unique())

2

# Exercise 4

In [7]:
data.isnull().sum(axis = 0)

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

# Exercise 5

In [8]:
max(data[data.origin == 'Asia']['fuel_efficiency_mpg'].values)

23.759122836520497

# Exercise 6

In [9]:
data['horsepower'].median()

149.0

In [10]:
data['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [11]:
data_hp = data['horsepower'].fillna(value=152.0)
data_hp

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [12]:
data_hp.median()

152.0

# Exercise 7

In [13]:
data[data['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [14]:
data_Asia = data[data['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
data_Asia

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [15]:
X = data_Asia.head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [16]:
XTX =  np.matmul(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [17]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [18]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [19]:
w =np.dot(np.matmul(XTX_inv, X.T), y)
w

array([0.01386421, 0.5049067 ])

In [20]:
w.sum()

0.5187709081074016